// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schemas/events.proto

package nraySchema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Event is a container for everything that happens
//at a node and should later on be handled by EventHandlers
type Event struct {
	NodeID      string               `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	NodeName    string               `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Timestamp   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Scannername string               `protobuf:"bytes,6,opt,name=scannername,proto3" json:"scannername,omitempty"`
	// Types that are valid to be assigned to EventData:
	//	*Event_Environment
	//	*Event_Result
	EventData            isEvent_EventData `protobuf_oneof:"EventData"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab30010df94cd8f, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *Event) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetScannername() string {
	if m != nil {
		return m.Scannername
	}
	return ""
}

type isEvent_EventData interface {
	isEvent_EventData()
}

type Event_Environment struct {
	Environment *EnvironmentInformation `protobuf:"bytes,7,opt,name=environment,proto3,oneof"`
}

type Event_Result struct {
	Result *ScanResult `protobuf:"bytes,8,opt,name=result,proto3,oneof"`
}

func (*Event_Environment) isEvent_EventData() {}

func (*Event_Result) isEvent_EventData() {}

func (m *Event) GetEventData() isEvent_EventData {
	if m != nil {
		return m.EventData
	}
	return nil
}

func (m *Event) GetEnvironment() *EnvironmentInformation {
	if x, ok := m.GetEventData().(*Event_Environment); ok {
		return x.Environment
	}
	return nil
}

func (m *Event) GetResult() *ScanResult {
	if x, ok := m.GetEventData().(*Event_Result); ok {
		return x.Result
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Environment)(nil),
		(*Event_Result)(nil),
	}
}

type ScanResult struct {
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Port   uint32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*ScanResult_Portscan
	//	*ScanResult_Zgrabscan
	Result               isScanResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ScanResult) Reset()         { *m = ScanResult{} }
func (m *ScanResult) String() string { return proto.CompactTextString(m) }
func (*ScanResult) ProtoMessage()    {}
func (*ScanResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab30010df94cd8f, []int{1}
}

func (m *ScanResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResult.Unmarshal(m, b)
}
func (m *ScanResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResult.Marshal(b, m, deterministic)
}
func (m *ScanResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResult.Merge(m, src)
}
func (m *ScanResult) XXX_Size() int {
	return xxx_messageInfo_ScanResult.Size(m)
}
func (m *ScanResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResult proto.InternalMessageInfo

func (m *ScanResult) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ScanResult) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type isScanResult_Result interface {
	isScanResult_Result()
}

type ScanResult_Portscan struct {
	Portscan *PortScanResult `protobuf:"bytes,8,opt,name=portscan,proto3,oneof"`
}

type ScanResult_Zgrabscan struct {
	Zgrabscan *ZGrab2ScanResult `protobuf:"bytes,9,opt,name=zgrabscan,proto3,oneof"`
}

func (*ScanResult_Portscan) isScanResult_Result() {}

func (*ScanResult_Zgrabscan) isScanResult_Result() {}

func (m *ScanResult) GetResult() isScanResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ScanResult) GetPortscan() *PortScanResult {
	if x, ok := m.GetResult().(*ScanResult_Portscan); ok {
		return x.Portscan
	}
	return nil
}

func (m *ScanResult) GetZgrabscan() *ZGrab2ScanResult {
	if x, ok := m.GetResult().(*ScanResult_Zgrabscan); ok {
		return x.Zgrabscan
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ScanResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ScanResult_Portscan)(nil),
		(*ScanResult_Zgrabscan)(nil),
	}
}

// EnvironmentInformation tells the server
//under which circumstances nodes are running
type EnvironmentInformation struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                   string   `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Pid                  string   `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Processname          string   `protobuf:"bytes,4,opt,name=processname,proto3" json:"processname,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Cpumodelname         string   `protobuf:"bytes,6,opt,name=cpumodelname,proto3" json:"cpumodelname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentInformation) Reset()         { *m = EnvironmentInformation{} }
func (m *EnvironmentInformation) String() string { return proto.CompactTextString(m) }
func (*EnvironmentInformation) ProtoMessage()    {}
func (*EnvironmentInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab30010df94cd8f, []int{2}
}

func (m *EnvironmentInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentInformation.Unmarshal(m, b)
}
func (m *EnvironmentInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentInformation.Marshal(b, m, deterministic)
}
func (m *EnvironmentInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentInformation.Merge(m, src)
}
func (m *EnvironmentInformation) XXX_Size() int {
	return xxx_messageInfo_EnvironmentInformation.Size(m)
}
func (m *EnvironmentInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentInformation.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentInformation proto.InternalMessageInfo

func (m *EnvironmentInformation) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *EnvironmentInformation) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *EnvironmentInformation) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *EnvironmentInformation) GetProcessname() string {
	if m != nil {
		return m.Processname
	}
	return ""
}

func (m *EnvironmentInformation) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EnvironmentInformation) GetCpumodelname() string {
	if m != nil {
		return m.Cpumodelname
	}
	return ""
}

// TCPScanResult contains the outcome of
//a TCP scan against a single port on a single host
type PortScanResult struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Open                 bool     `protobuf:"varint,3,opt,name=open,proto3" json:"open,omitempty"`
	Scantype             string   `protobuf:"bytes,4,opt,name=scantype,proto3" json:"scantype,omitempty"`
	Timeout              uint32   `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortScanResult) Reset()         { *m = PortScanResult{} }
func (m *PortScanResult) String() string { return proto.CompactTextString(m) }
func (*PortScanResult) ProtoMessage()    {}
func (*PortScanResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab30010df94cd8f, []int{3}
}

func (m *PortScanResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortScanResult.Unmarshal(m, b)
}
func (m *PortScanResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortScanResult.Marshal(b, m, deterministic)
}
func (m *PortScanResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortScanResult.Merge(m, src)
}
func (m *PortScanResult) XXX_Size() int {
	return xxx_messageInfo_PortScanResult.Size(m)
}
func (m *PortScanResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PortScanResult.DiscardUnknown(m)
}

var xxx_messageInfo_PortScanResult proto.InternalMessageInfo

func (m *PortScanResult) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *PortScanResult) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PortScanResult) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *PortScanResult) GetScantype() string {
	if m != nil {
		return m.Scantype
	}
	return ""
}

func (m *PortScanResult) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type ZGrab2ScanResult struct {
	JsonResult           *_struct.Value `protobuf:"bytes,1,opt,name=jsonResult,proto3" json:"jsonResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ZGrab2ScanResult) Reset()         { *m = ZGrab2ScanResult{} }
func (m *ZGrab2ScanResult) String() string { return proto.CompactTextString(m) }
func (*ZGrab2ScanResult) ProtoMessage()    {}
func (*ZGrab2ScanResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab30010df94cd8f, []int{4}
}

func (m *ZGrab2ScanResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZGrab2ScanResult.Unmarshal(m, b)
}
func (m *ZGrab2ScanResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZGrab2ScanResult.Marshal(b, m, deterministic)
}
func (m *ZGrab2ScanResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZGrab2ScanResult.Merge(m, src)
}
func (m *ZGrab2ScanResult) XXX_Size() int {
	return xxx_messageInfo_ZGrab2ScanResult.Size(m)
}
func (m *ZGrab2ScanResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ZGrab2ScanResult.DiscardUnknown(m)
}

var xxx_messageInfo_ZGrab2ScanResult proto.InternalMessageInfo

func (m *ZGrab2ScanResult) GetJsonResult() *_struct.Value {
	if m != nil {
		return m.JsonResult
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "nraySchema.Event")
	proto.RegisterType((*ScanResult)(nil), "nraySchema.ScanResult")
	proto.RegisterType((*EnvironmentInformation)(nil), "nraySchema.EnvironmentInformation")
	proto.RegisterType((*PortScanResult)(nil), "nraySchema.PortScanResult")
	proto.RegisterType((*ZGrab2ScanResult)(nil), "nraySchema.ZGrab2ScanResult")
}

func init() { proto.RegisterFile("schemas/events.proto", fileDescriptor_3ab30010df94cd8f) }

var fileDescriptor_3ab30010df94cd8f = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0x8d, 0x14, 0xdb, 0x91, 0xc6, 0xbf, 0x5f, 0x08, 0x4b, 0x31, 0x42, 0x04, 0x6a, 0x74, 0xf2,
	0x49, 0x2e, 0x29, 0x94, 0x1c, 0x7a, 0x0a, 0x49, 0x9b, 0xf4, 0x50, 0xca, 0xa6, 0xf4, 0xd0, 0xdb,
	0x5a, 0xde, 0x38, 0x2e, 0xd6, 0x8e, 0xd8, 0x5d, 0x05, 0xd2, 0x0f, 0xd0, 0x8f, 0xd1, 0xcf, 0x51,
	0xfa, 0xe9, 0xca, 0x8e, 0xfe, 0xad, 0x4d, 0x4e, 0xda, 0xa7, 0x79, 0xf3, 0x66, 0xf6, 0xbd, 0x85,
	0x57, 0xa6, 0x78, 0x94, 0xa5, 0x30, 0x4b, 0xf9, 0x24, 0x95, 0x35, 0x79, 0xa5, 0xd1, 0x22, 0x03,
	0xa5, 0xc5, 0xf3, 0x3d, 0x55, 0xd2, 0xd7, 0x1b, 0xc4, 0xcd, 0x4e, 0x2e, 0xa9, 0xb2, 0xaa, 0x1f,
	0x96, 0x76, 0x5b, 0x4a, 0x63, 0x45, 0x59, 0x35, 0xe4, 0xf4, 0xfc, 0x90, 0x60, 0xac, 0xae, 0x0b,
	0xdb, 0x54, 0xb3, 0xdf, 0x21, 0x8c, 0x6f, 0x9c, 0x36, 0x9b, 0xc1, 0x44, 0xe1, 0x5a, 0xde, 0x5d,
	0x27, 0xc1, 0x3c, 0x58, 0xc4, 0xbc, 0x45, 0x2c, 0x85, 0xc8, 0x9d, 0x3e, 0x8b, 0x52, 0x26, 0x21,
	0x55, 0x7a, 0xcc, 0x2e, 0x21, 0xee, 0xc7, 0x25, 0xc7, 0xf3, 0x60, 0x31, 0xbd, 0x48, 0xf3, 0x66,
	0x5e, 0xde, 0xcd, 0xcb, 0xbf, 0x76, 0x0c, 0x3e, 0x90, 0xd9, 0x1c, 0xa6, 0xa6, 0x10, 0x4a, 0x49,
	0xad, 0x9c, 0xf0, 0x84, 0x84, 0xfd, 0x5f, 0xec, 0x03, 0x4c, 0xa5, 0x7a, 0xda, 0x6a, 0x54, 0xa5,
	0x54, 0x36, 0x39, 0x21, 0xf5, 0x2c, 0x1f, 0xae, 0x9e, 0xdf, 0x0c, 0xe5, 0x3b, 0xf5, 0x80, 0xba,
	0x14, 0x76, 0x8b, 0xea, 0xf6, 0x88, 0xfb, 0x8d, 0xec, 0x0d, 0x4c, 0xb4, 0x34, 0xf5, 0xce, 0x26,
	0x11, 0x49, 0xcc, 0x7c, 0x89, 0xfb, 0x42, 0x28, 0x4e, 0xd5, 0xdb, 0x23, 0xde, 0xf2, 0xae, 0xa6,
	0x10, 0x93, 0x25, 0xd7, 0xc2, 0x8a, 0xec, 0x6f, 0x00, 0x30, 0xb0, 0x9c, 0x4b, 0x56, 0xe8, 0x8d,
	0xb4, 0xc9, 0xa8, 0x71, 0xa9, 0x41, 0x8c, 0xc1, 0xa8, 0x42, 0x6d, 0x93, 0xf1, 0x3c, 0x58, 0xfc,
	0xcf, 0xe9, 0xcc, 0x2e, 0x21, 0x72, 0x5f, 0x77, 0xa9, 0x76, 0x76, 0xea, 0xcf, 0xfe, 0x82, 0xda,
	0xee, 0xcd, 0xef, 0xd9, 0xec, 0x3d, 0xc4, 0x3f, 0x37, 0x5a, 0xac, 0xa8, 0x35, 0xa6, 0xd6, 0x73,
	0xbf, 0xf5, 0xfb, 0x47, 0x2d, 0x56, 0x17, 0x7b, 0xcd, 0x43, 0xc3, 0x55, 0xd4, 0xdd, 0x38, 0xfb,
	0x13, 0xc0, 0xec, 0x65, 0x97, 0x5c, 0xac, 0x8f, 0x68, 0x2c, 0xb9, 0xdf, 0x04, 0xde, 0x63, 0x76,
	0x0a, 0x21, 0x9a, 0x36, 0xec, 0x10, 0x0d, 0x3b, 0x83, 0xe3, 0x6a, 0xbb, 0xa6, 0x80, 0x63, 0xee,
	0x8e, 0x2e, 0xbe, 0x4a, 0x63, 0x21, 0x8d, 0x21, 0x81, 0xc6, 0x0b, 0xff, 0x97, 0xd3, 0xaf, 0x4d,
	0x9b, 0xee, 0xb8, 0xd1, 0xef, 0x30, 0xcb, 0xe0, 0xbf, 0xa2, 0xaa, 0x4b, 0x5c, 0xcb, 0x9d, 0x97,
	0xfe, 0xde, 0xbf, 0xec, 0x57, 0x00, 0xa7, 0xfb, 0x0e, 0x79, 0xde, 0x07, 0x2f, 0x7a, 0x1f, 0x7a,
	0xde, 0x33, 0x18, 0x61, 0x25, 0x15, 0xed, 0x1c, 0x71, 0x3a, 0xbb, 0x95, 0x9c, 0x3f, 0xf6, 0xb9,
	0xea, 0x36, 0xee, 0x31, 0x4b, 0xe0, 0xc4, 0x3d, 0x4e, 0xac, 0xbb, 0x08, 0x3b, 0x98, 0x7d, 0x82,
	0xb3, 0x43, 0xbb, 0xd9, 0x3b, 0x80, 0x1f, 0x06, 0x5b, 0x44, 0xdb, 0xb8, 0x77, 0x75, 0xf8, 0xf0,
	0xbf, 0x89, 0x5d, 0x2d, 0xb9, 0xc7, 0x5c, 0x4d, 0xa8, 0xf6, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x8b, 0x35, 0x95, 0xd7, 0x03, 0x00, 0x00,
}
